version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis
    ports:
      - "6379:6379"

  server:
    build:
      context: ./server
    ports:
      - "8800:8800" # Map server's port 8800 to host's port 8800
    env_file:
      - ./server/.env # Use the .env file for the server service
    depends_on:
      - redis
      - rabbitmq

  client:
    build:
      context: ./client
    ports:
      - "3000:3000" # Map client's port 3000 to host's port 3000
    depends_on:
      - server # Specify that the client service depends on the server service
    env_file:
      - ./client/.env # Use the .env file for the client service
